### PR TITLE
Automate publishing to NPM

### PR DESCRIPTION
**Pull request by jasongitmail**
I thought this might be helpful for you.

You'd just need to [generate an NPM Token](https://docs.npmjs.com/creating-and-viewing-access-tokens) with the `automation` permission and add `NPM_TOKEN` as a secret on this Github repo.

Then any PR that is merged to `main` that bumps the version # in package.json will be automatically published to NPM.

There don't appear to be any tests in `etherCorps/sveltekit-og` currently, so I left a comment there; enabling this line will only publish to NPM only if tests pass successfully.

### CODE REVIEW

**Comment by theetherGit** [comment]
@jasongitmail we have to build and add package dir to github, or you have to change config to make to build then change dir and then publish.

**Comment by theetherGit** [comment]
I think it looks good to go now. 
We can test it as i'm going to push version for your patches.

**Comment by jasongitmail** [comment]
Updated. The `package` property is [a path to a dir that contains the package.json](https://github.com/JS-DevTools/npm-publish#usage-1) of the package to be deployed, so this should work.

**Comment by theetherGit** [comment]
@jasongitmail please update publish file `action` node installation error.

**Comment by jasongitmail** [comment]
Oh shoot. I wanted to try `lts` because noticed [it in the docs](https://github.com/actions/setup-node#usage). I have used a number in the past; will switch to that.

**Pull request merged**
