### PR TITLE
use node-version:18 in Github Action

### PR DESCRIPTION
**Pull request by jasongitmail**

### CODE REVIEW

**Comment by theetherGit** [comment]
@jasongitmail so sorry i forgot to mention if you wanna use pnpm in actions you have to install it.

**Comment by jasongitmail** [comment]
ohh What pnpm version do you want to use?

**Comment by theetherGit** [comment]
i think i'm working on latest.

**Comment by jasongitmail** [comment]
went with 7 for now, based on the [action's docs ](https://github.com/marketplace/actions/setup-pnpm). Could try 8 too if you prefer and see if it works

**Comment by theetherGit** [comment]
it's ok add it first we have to test it. so no problem.

**Pull request merged**
